leagues:
  DGW2022:
    title: Zimowy Puchar DGW 2022
    competition_ids: [1963931,1989984,1995699,2003169,2004158,2008480,2014161,2020455,2025408, 2031939]
  DGW2023:
    title: Zimowy Puchar DGW - Sezon VII
    competition_ids: [2398354,2398357,2398358,2398359,2398360,2429328,2433809,2439393,2439394,2439396]
  DGW2024:
    title: Zimowy Puchar DGW - Sezon VIII
    competition_ids: [2806560,2806563,2806564,2819710, 2825130]
  DGW2025:
    title: Zimowy Puchar DGW - Sezon IX
    competition_ids: [3161598,3169353,3176993]
    ignore_holes: { 3169353: [17,18] }

rating:
  outlier_fraction: 0.25
  prop_min_rating: 500
