
leagues:
  DGW2022:
    title: Zimowy Puchar DGW 2022
    competition_ids: [1963931,1989984,1995699,2003169,2004158,2008480,2014161,2020455,2025408, 2031939]
    categories: {"OPEN", "WOMEN", "MASTERS", "JUNIOR"}
    scoring: proportional
    
  DGW2023:
    title: Zimowy Puchar DGW - Sezon VII
    competition_ids: [2398354,2398357,2398358,2398359,2398360,2429328,2433809,2439393,2439394,2439396]
    categories: {"OPEN", "WOMEN", "MASTERS", "JUNIOR"}
    scoring: proportional
    
  DGW2024:
    title: Zimowy Puchar DGW - Sezon VIII
    competition_ids: [2806560,2806563,2806564,2819710, 2825130,2828964,2832280,2837516,2842339,2850504]
    categories: {"OPEN", "WOMEN", "MASTERS", "JUNIOR"}
    scoring: proportional
    
  DGW2025:
    title: Zimowy Puchar DGW - Sezon IX
    competition_ids: [3161598,3169353,3176993,3182408,3185707,3192700,3198732,3201276,3208850,3214050]
    ignore_holes: { 3169353: [17,18] }
    categories: {"OPEN", "WOMEN", "MASTERS", "JUNIOR"}
    scoring: proportional
    
  TLDG2025:
    title: TrÃ³jmiejska Liga Disc Golfa 2025
    competition_ids: [3297579, 3297585, 3297587, 3297591, 3297593, 3297595, 3297596, 3297597, 3297599, 3297603]
    ccompetition_ids: [3297587]
    categories: ['OPEN','MIXED AMATEUR', 'NOVICE']
    scoring: dgpt100
    
  DGW2026:
    title: Zimowy Puchar DGW - Sezon X
    competition_ids: [3478960, 3505500]
    ignore_holes: {  }
    categories: {"BLUE RAH >900", "WHITE RAD 850-899", "RED RAE 800-849", "GREEN RAF 751-799", "PURPLE 0-750"}
    scoring: dgpt100
    
rating:
  outlier_fraction: 0.15
  prop_min_rating: 700

dgw:
  default_categories: [ 'OPEN', 'WOMEN', 'MASTERS', 'JUNIOR' ]
  scoring_tables:
    proportional:
      type: proportional
    dgpt100:
      type: fixed
      points: [100,85,75,69,64,60,57,54,52,50,48,46,44,42,40,38,36,34,32,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,2,2]
